IO_USERNAME: gardbot
IO_KEY: aio_UcCS14tcOJc5An4B1P40qc6Jfcv2

feed: 
  input:
    sensor:
      - s0001
      - s0002
      - s0003
      - s0004
    tempHumid:
      - dht0001
  output:
  - p0001
  - p0002
  - p0003
  - p0004
      
realServer:
  USERNAME: 
    - hoanduy27
  KEY:
    - aio_UpfD80mbJsiHPstfJjd0efnKnoYr
  # dht:
  #   IO_OWNER: CSE_BBC
  #   feedId: bk-iot-temp-humid
  soil:
    IO_OWNER: hoanduy27
    feedId: bk-iot-soil
  # relay:
  #   IO_OWNER: CSE_BBC1
  #   feedId: bk-iot-relay


firebase:
  secret: fzXrGa22e78ybBS92CCNuUsxt3j9ciWJ3Jhu7WbS
  email: hoanduy27@gmail.com
  db: https://garbbot-default-rtdb.asia-southeast1.firebasedatabase.app/
